name: Java CI with Maven

on:
  push:
    branches:
      - main  # Déclencher le pipeline lors d'un push sur la branche principale
  pull_request:
    branches:
      - main  # Déclencher lors d'une pull request vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser une machine Ubuntu pour exécuter le pipeline

    steps:
      # Étape 1: Vérifier le code source depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Configurer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Mettre à jour pour JDK 17
          distribution: 'temurin'  # Utilisation de la distribution Temurin (officielle)

      # Étape 3: Compiler le projet avec Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests=true  # Compiler sans exécuter les tests

      # Étape 4: Exécuter les tests
      - name: Run tests with Maven
        run: mvn test  # Exécuter les tests après la compilation

      # Étape 5 (optionnelle) : Publier l'artefact du build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-java-artifact
          path: target/*.jar  # Spécifier le chemin vers les artefacts générés (fichiers JAR)
